# Generated by Django 3.2.20 on 2023-11-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_checker', '0002_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='country_banned_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
